app:
  port: 5000
  debug: false
mysql:
  host: 192.168.100.2
  database: foodlove
  username: foodlove
  password: foodlove
mongo:
  host: "mongodb://activities:activities@192.168.100.4:27017/activities?authMechanism=SCRAM-SHA-1"
  database: activities
